name: rnaseq
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - zlib=1.2.13
  - openssl
  - samtools=1.19
  - htslib=1.19
  - star=2.7.10b
  - fastp=0.23.4
  - subread=2.0.3
  - pyyaml
  - numpy
  - ncurses